# Generated by Django 2.2.26 on 2022-03-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=4)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floppa.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Necklace')),
                ('wishlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Necklace')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Cart')),
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Necklace')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floppa.Customer'),
        ),
    ]
