<<<<<<< Updated upstream
# Generated by Django 3.1 on 2022-03-21 12:02
=======
# Generated by Django 3.1 on 2022-03-19 14:27
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
<<<<<<< Updated upstream
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('userID', models.AutoField(default=601, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
>>>>>>> Stashed changes
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=4)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
<<<<<<< Updated upstream
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('orderID', models.AutoField(max_length=8, primary_key=True, serialize=False, unique=True)),
>>>>>>> Stashed changes
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
<<<<<<< Updated upstream
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('wishlistID', models.AutoField(max_length=8, primary_key=True, serialize=False, unique=True)),
>>>>>>> Stashed changes
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floppa.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.necklace')),
                ('wishlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('quantity', models.IntegerField(default=0)),
=======
                ('quantity', models.IntegerField()),
>>>>>>> Stashed changes
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.necklace')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('quantity', models.IntegerField(default=0)),
=======
                ('quantity', models.IntegerField()),
>>>>>>> Stashed changes
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.cart')),
                ('necklaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.necklace')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floppa.customer'),
        ),
    ]
